
name: Handle prod_version Tag

on:
  push:
    tags:
      - prod_version

jobs:
  manage-prod-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "Zayam Amjad"
          git config --global user.email "you@example.com"

      - name: Delete existing prod_version tag (if any)
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/prod_version"; then
            echo "Tag 'prod_version' already exists on remote. Deleting it..."
            git push --delete origin prod_version
          else
            echo "No existing prod_version tag found."
          fi

      - name: Re-push prod_version tag
        run: |
          git tag prod_version
          git --tags
